name: linkedgates_task
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.7.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  internet_connection_checker: ^3.0.1
  redacted: ^1.0.13
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/images/
  - assets/fonts/YsabeauSC-Medium.ttf

fonts:
  - family: YsabeauSC
    fonts:
      - asset: assets/fonts/YsabeauSC-Medium.ttf
