name: linkedgates_task
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.7.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
